name: atelyam
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ FIREBASE & NOTIFICATIONS
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  flutter_local_notifications: ^19.0.0

  # ðŸ“¦ STATE MANAGEMENT
  get: ^4.6.6
  get_storage: ^2.0.0
  upgrader: ^10.3.0

  # ðŸ–¼ï¸ UI & UX
  iconly: ^1.0.1
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.1.1
  pull_to_refresh: ^2.0.0
  photo_view: ^0.15.0
  flutter_widget_from_html: ^0.15.3
  sliver_tools: ^0.2.0

  # âš™ï¸ UTILS
  flutter_image_compress: ^2.4.0
  image_picker: ^0.8.5+3
  permission_handler: ^11.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.1.12
  dio: ^5.9.0
  hugeicons: ^0.0.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
    - assets/image/fasonlar/
    - assets/image/flags/
    - assets/image/patterns/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700

    - family: Bell
      fonts:
        - asset: assets/fonts/BellRegular.otf
          weight: 400
